In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
dataset= pd.read_csv("/home/neeraj/Downloads/dataset.csv")

In [5]:
dataset=dataset.drop('Unnamed: 0', axis=1)

In [6]:
dataset

CommissionAmount  PaidRankID       PV       GV       DV
0                  3.00         0.0    0.000    0.000    0.000
1                 16.69        10.0  166.940  166.940  166.940
2                 16.69         0.0    0.000    0.000    0.000
3                  1.00         0.0    0.000    0.000    0.000
4                  2.00        10.0  590.610  590.610  590.610
...                 ...         ...      ...      ...      ...
49767              9.00        20.0  281.868  387.838  387.838
49768             10.78        10.0  107.940  107.940  107.940
49769             16.19        10.0  107.940  107.940  107.940
49770              3.30        10.0  193.910  193.910  193.910
49771              4.50        10.0   99.940   99.940   99.940

[49772 rows x 5 columns]

Encoding the Value on the basis of PaidRankId

In [7]:
from sklearn.preprocessing import OneHotEncoder
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(dataset[['PaidRankID']]).toarray())
# merge with main df bridge_df on key values
dataset = dataset.join(enc_df)
dataset

CommissionAmount  PaidRankID       PV       GV       DV    0    1    2  \
0                  3.00         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
1                 16.69        10.0  166.940  166.940  166.940  0.0  1.0  0.0   
2                 16.69         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
3                  1.00         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
4                  2.00        10.0  590.610  590.610  590.610  0.0  1.0  0.0   
...                 ...         ...      ...      ...      ...  ...  ...  ...   
49767              9.00        20.0  281.868  387.838  387.838  0.0  0.0  1.0   
49768             10.78        10.0  107.940  107.940  107.940  0.0  1.0  0.0   
49769             16.19        10.0  107.940  107.940  107.940  0.0  1.0  0.0   
49770              3.30        10.0  193.910  193.910  193.910  0.0  1.0  0.0   
49771              4.50        10.0   99.940   99.940   99.940  0.0  1.0  0.0   

         3    4    5    6    7    8    9  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
49767  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49768  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49769  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49770  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49771  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[49772 rows x 15 columns]

In [8]:
dataset

CommissionAmount  PaidRankID       PV       GV       DV    0    1    2  \
0                  3.00         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
1                 16.69        10.0  166.940  166.940  166.940  0.0  1.0  0.0   
2                 16.69         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
3                  1.00         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
4                  2.00        10.0  590.610  590.610  590.610  0.0  1.0  0.0   
...                 ...         ...      ...      ...      ...  ...  ...  ...   
49767              9.00        20.0  281.868  387.838  387.838  0.0  0.0  1.0   
49768             10.78        10.0  107.940  107.940  107.940  0.0  1.0  0.0   
49769             16.19        10.0  107.940  107.940  107.940  0.0  1.0  0.0   
49770              3.30        10.0  193.910  193.910  193.910  0.0  1.0  0.0   
49771              4.50        10.0   99.940   99.940   99.940  0.0  1.0  0.0   

         3    4    5    6    7    8    9  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
49767  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49768  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49769  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49770  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49771  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[49772 rows x 15 columns]

Using KerasRegressor (Regression problem) Algorithm

In [15]:
import pandas
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from keras.layers import LSTM
from sklearn.pipeline import Pipeline
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras import Sequential
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers.experimental import preprocessing
...

Using TensorFlow backend.


Ellipsis

In [454]:
columns= dataset.columns.tolist()
columns.remove('PaidRankID')
label='CommissionAmount'
columns.remove(label)

In [455]:
X= dataset[columns]
Y= dataset[[label]]

Splitting the data into train and test

In [456]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [457]:
X_train

PV         GV         DV    0    1    2    3    4    5    6    7  \
34644   153.940    153.940    153.940  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
38928     9.990      9.990      9.990  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
32841     0.000      0.000      0.000  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
36183     0.000      0.000      0.000  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4562    670.234   2026.186   2026.186  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
...         ...        ...        ...  ...  ...  ...  ...  ...  ...  ...  ...   
11284  3016.484  12386.938  12386.938  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
44732   938.584   1142.984   1142.984  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
38158   689.220   1025.100   1025.100  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
860       0.000      0.000      0.000  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15795     0.000      0.000      0.000  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

         8    9  
34644  0.0  0.0  
38928  0.0  0.0  
32841  0.0  0.0  
36183  0.0  0.0  
4562   0.0  0.0  
...    ...  ...  
11284  0.0  0.0  
44732  0.0  0.0  
38158  0.0  0.0  
860    0.0  0.0  
15795  0.0  0.0  

[34840 rows x 13 columns]

Normalizing the data

In [458]:
normalizer = preprocessing.Normalization()

In [459]:
normalizer.adapt(np.array(X_train))

In [460]:
normalizer.mean.numpy()

array([4.5462665e+02, 1.3609946e+03, 3.1454363e+03, 3.9239380e-01,
       3.8596442e-01, 6.6561423e-02, 3.1745121e-02, 4.5177955e-02,
       1.9747417e-02, 3.5993110e-02, 1.3375430e-02, 4.6785306e-03,
       4.3628016e-03], dtype=float32)

In [461]:
model.add(normalizer)
model.add(Dense(1))

In [394]:
model

In [469]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [470]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [471]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [472]:
X_test_scaled.max()

24.1189173320669

Preparing the Model

In [473]:
model=Sequential()

In [474]:
look_back=1

In [475]:
# model.add(Dense(8, activation='relu', input_shape=[X_train.shape[1]]))
# model.add(Dense(16, activation='relu'))
# model.add(Dense(64, activation='relu'))
# model.add(Dense(128, activation='relu'))

# Add an input layer 
model.add(Dense(12, input_shape=[X_train.shape[1]],
activation='relu'))
model.add(Dense(512,  activation='relu'))
model.add(Dense(256,  activation='relu'))
model.add(Dense(128,  activation='relu'))
model.add(Dense(128,  activation='relu'))
model.add(Dense(1,  activation='linear'))


In [476]:
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
#model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])



In [477]:
history = model.fit(X_train_scaled, y_train, validation_split=0.2,batch_size=32, epochs=15)

Epoch 1/15
871/871 [==============================] - 6s 7ms/step - loss: 202.8731 - accuracy: 0.0032 - val_loss: 200.2852 - val_accuracy: 0.0034
Epoch 2/15
871/871 [==============================] - 5s 6ms/step - loss: 194.5854 - accuracy: 0.0033 - val_loss: 190.0724 - val_accuracy: 0.0034
Epoch 3/15
871/871 [==============================] - 5s 6ms/step - loss: 192.9472 - accuracy: 0.0033 - val_loss: 188.3185 - val_accuracy: 0.0034
Epoch 4/15
871/871 [==============================] - 6s 7ms/step - loss: 191.9994 - accuracy: 0.0033 - val_loss: 194.7603 - val_accuracy: 0.0034
Epoch 5/15
871/871 [==============================] - 5s 6ms/step - loss: 192.4874 - accuracy: 0.0033 - val_loss: 184.2233 - val_accuracy: 0.0034
Epoch 6/15
871/871 [==============================] - 5s 6ms/step - loss: 191.6758 - accuracy: 0.0033 - val_loss: 185.2673 - val_accuracy: 0.0034
Epoch 7/15
871/871 [==============================] - 6s 6ms/step - loss: 190.6380 - accuracy: 0.0033 - val_loss: 186.3032 -

In [478]:
model.evaluate(X_test_scaled, y_test)

467/467 [==============================] - 1s 2ms/step - loss: 205.9493 - accuracy: 0.0038


[205.9492645263672, 0.003817305201664567]

In [479]:
to_predict = X_train_scaled

In [480]:
predictions = model.predict(to_predict)

In [481]:
predictions[:10]

array([[ 8.126039 ],
       [10.467093 ],
       [10.527342 ],
       [10.527342 ],
       [11.630839 ],
       [18.079391 ],
       [ 8.447401 ],
       [20.702106 ],
       [10.2447815],
       [10.527342 ]], dtype=float32)

In [482]:
y_train[:10]

CommissionAmount
34644             15.39
38928              1.00
32841              1.50
36183              8.00
4562              15.00
2683               6.23
15353              9.50
45213              5.05
2281               4.50
29780             13.00

RANDOM FOREST ALGORITHM

In [29]:
df=dataset

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns

In [31]:
features= pd.get_dummies(df)

In [32]:
features

CommissionAmount  PaidRankID       PV       GV       DV    0    1    2  \
0                  3.00           0    0.000    0.000    0.000  1.0  0.0  0.0   
1                 16.69           1  166.940  166.940  166.940  0.0  1.0  0.0   
2                 16.69           0    0.000    0.000    0.000  1.0  0.0  0.0   
3                  1.00           0    0.000    0.000    0.000  1.0  0.0  0.0   
4                  2.00           1  590.610  590.610  590.610  0.0  1.0  0.0   
...                 ...         ...      ...      ...      ...  ...  ...  ...   
49767              9.00           2  281.868  387.838  387.838  0.0  0.0  1.0   
49768             10.78           1  107.940  107.940  107.940  0.0  1.0  0.0   
49769             16.19           1  107.940  107.940  107.940  0.0  1.0  0.0   
49770              3.30           1  193.910  193.910  193.910  0.0  1.0  0.0   
49771              4.50           1   99.940   99.940   99.940  0.0  1.0  0.0   

         3    4    5    6    7    8    9  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
49767  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49768  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49769  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49770  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49771  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[49772 rows x 15 columns]

In [33]:
labels = np.array(features['CommissionAmount'])

In [34]:
features= features.drop('CommissionAmount', axis = 1)

In [35]:
feature_list = list(features.columns)

In [36]:
features = np.array(features)

Splitting the Data

In [37]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [56]:
baseline_preds = test_features[:, feature_list.index('PaidRankID')]
baseline_preds

array([0., 1., 1., ..., 1., 0., 1.])

In [57]:
baseline_errors = abs(baseline_preds - test_labels)

In [58]:
baseline_errors

array([11.  ,  5.5 ,  3.5 , ...,  3.  ,  3.  , 28.99])

In [59]:
print('Average baseline error: ', round(np.mean(baseline_errors), 2))

Average baseline error:  11.23


Preparing The Model

In [60]:
from sklearn.ensemble import RandomForestRegressor

In [61]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

In [62]:
rf.fit(train_features, train_labels)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [63]:
predictions = rf.predict(test_features)

In [64]:
errors = abs(predictions - test_labels)

In [65]:
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 7.64 degrees.


In [66]:
mape = 100 * (errors / test_labels)

In [67]:
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: -16.91 %.


DECISION TREE ALGORITHM

In [23]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns

In [125]:
dataset

CommissionAmount  PaidRankID       PV       GV       DV    0    1    2  \
0                  3.00         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
1                 16.69        10.0  166.940  166.940  166.940  0.0  1.0  0.0   
2                 16.69         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
3                  1.00         0.0    0.000    0.000    0.000  1.0  0.0  0.0   
4                  2.00        10.0  590.610  590.610  590.610  0.0  1.0  0.0   
...                 ...         ...      ...      ...      ...  ...  ...  ...   
49767              9.00        20.0  281.868  387.838  387.838  0.0  0.0  1.0   
49768             10.78        10.0  107.940  107.940  107.940  0.0  1.0  0.0   
49769             16.19        10.0  107.940  107.940  107.940  0.0  1.0  0.0   
49770              3.30        10.0  193.910  193.910  193.910  0.0  1.0  0.0   
49771              4.50        10.0   99.940   99.940   99.940  0.0  1.0  0.0   

         3    4    5    6    7    8    9  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
49767  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49768  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49769  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49770  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
49771  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[49772 rows x 15 columns]

In [35]:
x= dataset[columns]
y= dataset[[label]]

Splitting the Data

In [67]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.60, random_state=42)


In [68]:
DecisionTreeRegModel= DecisionTreeRegressor()

In [69]:
DecisionTreeRegModel.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [70]:
y_pred= DecisionTreeRegModel.predict(x_test)

In [71]:
y_pred

array([10.50207582, -2.5       ,  4.75391813, ..., 10.50207582,
       19.79      , 10.50207582])

In [72]:
mse= mean_squared_error(y_test,y_pred)
mse

241.2121592157064

In [73]:
y_test[:5]

CommissionAmount
32657             11.00
23198              6.50
29909              4.50
17644             25.49
3732              30.49

In [74]:
y_pred[:5]

array([10.50207582, -2.5       ,  4.75391813,  2.8       , 44.19      ])

In [139]:
X= dataset[columns]

y= dataset[[label]]

In [140]:
X

PaidRankID       PV       GV       DV    0    1    2    3    4    5  \
0             0.0    0.000    0.000    0.000  1.0  0.0  0.0  0.0  0.0  0.0   
1            10.0  166.940  166.940  166.940  0.0  1.0  0.0  0.0  0.0  0.0   
2             0.0    0.000    0.000    0.000  1.0  0.0  0.0  0.0  0.0  0.0   
3             0.0    0.000    0.000    0.000  1.0  0.0  0.0  0.0  0.0  0.0   
4            10.0  590.610  590.610  590.610  0.0  1.0  0.0  0.0  0.0  0.0   
...           ...      ...      ...      ...  ...  ...  ...  ...  ...  ...   
49767        20.0  281.868  387.838  387.838  0.0  0.0  1.0  0.0  0.0  0.0   
49768        10.0  107.940  107.940  107.940  0.0  1.0  0.0  0.0  0.0  0.0   
49769        10.0  107.940  107.940  107.940  0.0  1.0  0.0  0.0  0.0  0.0   
49770        10.0  193.910  193.910  193.910  0.0  1.0  0.0  0.0  0.0  0.0   
49771        10.0   99.940   99.940   99.940  0.0  1.0  0.0  0.0  0.0  0.0   

         6    7    8    9  
0      0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  
49767  0.0  0.0  0.0  0.0  
49768  0.0  0.0  0.0  0.0  
49769  0.0  0.0  0.0  0.0  
49770  0.0  0.0  0.0  0.0  
49771  0.0  0.0  0.0  0.0  

[49772 rows x 14 columns]

In [141]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.60, random_state=42)

In [131]:
from sklearn.preprocessing import StandardScaler
sc_x_train = StandardScaler()
sc_y_train = StandardScaler()
x_train = sc_X.fit_transform(x_train)
y_train= sc_y.fit_transform(y_train)

In [142]:
y_test

CommissionAmount
32657             11.00
23198              6.50
29909              4.50
17644             25.49
3732              30.49
...                 ...
15759              9.55
37190             12.04
41706              7.50
47863             11.00
26887             19.79

[29864 rows x 1 columns]

SVM Algorithm

In [143]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt

In [144]:
regressor = SVR(kernel='rbf')
regressor.fit(x_train,y_train)

/home/neeraj/.local/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [145]:
y_pred = regressor.predict(x_test)
y_pred[:5]

array([7.13672856, 8.19148528, 7.28891217, 9.09469084, 9.71286054])

In [146]:
y_test[:5]

CommissionAmount
32657             11.00
23198              6.50
29909              4.50
17644             25.49
3732              30.49

In [147]:
mse= mean_squared_error(y_test,y_pred)
mse

223.65313345352885